global using System.Net.Mime;
global using System.ComponentModel.DataAnnotations.Schema;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.AspNetCore.Mvc;
global using API;
global using API.Entities;
global using API.Data;
global using API.Middlewares;
global using API.DTOs;